### PR TITLE
update protocol to send keycode and charcode together

### PR DESCRIPTION
**Pull request by 9gix**
@bloodelves88 I'm proposing that we send both UEKeyCode and UECharCode. Hence there is no need for the type distinction. 

If it is not found in the UECharCode, then it is UEKeyCode.

This PR is Related to https://github.com/insert-coin/RemoteController/pull/2

### CODE REVIEW

**Comment by 9gix** [comment]
I've tried the CharCode (`F1`, `F2`, `F3`, Mouse button, etc... ), and it is supposed to be working. 
Make sure you're using the https://github.com/insert-coin/RemoteController/pull/2 changes

**Comment by bloodelves88** [comment]
Try these keys:
.
[
-
\

They are triggering the CharCode value in UE4 instead of the KeyCode value.

Also, no matter what I press, the CharCode == KeyCode. No point having two different variables like that. This is no different from the previous code.

**Comment by 9gix** [comment]
What's wrong with the 4 symbols that you mentioned? (`.`, `[`, `-`, `\`)
To what I understand, if they have a specific charcode then it is expected to trigger charcode instead of keycode. 

I'm concern about the assumption of `CharCode == KeyCode`, because looking the function it takes in 2 integer parameter. Why they don't just take 1 parameter if they are the same?
Although so far, It has to be the same, if it is different, it won't work.

**Comment by bloodelves88** [comment]
Those 4 keys share the same numerical code with 4 other keys. For example, `.` shares the code 46 with the 'delete' key. Because of this, when I press `.`, delete is triggered instead. The only difference is that `.` is KeyCode 46, and 'delete' is CharCode 46. GetKeyFromCodes() does not seem to be able to differentiate this properly, which is why I suggested using a flag to hack it into getting the correct FKey. 

I am not assuming that CharCode == KeyCode. It is the behaviour that I observe in your code. It is never different. I just think it is slightly odd, but I am not against it.

**Comment by bloodelves88** [comment]
I'll merge this for now. I believe this is theoretically the correct way to send, but it is not working properly yet. Some more tweaks need to be done.

**Pull request merged**
