### PR TITLE
Launcher basic style

### PR DESCRIPTION
**Pull request by zeanne**

### CODE REVIEW

**Comment by bloodelves88** [comment]
Use password field for password box

**Comment by 9gix** [comment]
fix the `.gitignore` you are commiting file that is not relevant e.g. DS_Store.

**Comment by bloodelves88** [comment]
Just ignore the failing check. It's because your branch doesn't have the `.travis.yml` file yet.

**Comment by 9gix** [comment]
@zeanne @bloodelves88 All test pass :+1:

**Pull request merged**
